#!/usr/bin/env node
// Generate every derived surface from catalog/catalog.json and
// catalog/taxonomy.json. Nothing here is hand-edited, and CI proves it by
// regenerating and diffing.
//
//   node scripts/generate.mjs            write
//   node scripts/generate.mjs --check    fail if any output would change
//
// WHY THIS EXISTS: the pilot maintained llms.txt and four plugin manifests by
// hand. They drifted, and two repository-wide audits missed them because plugin
// manifests hide in dot-directories as .json. Generating them from one source
// makes drift a build failure instead of a discovery.

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';

const CATALOG = JSON.parse(readFileSync('catalog/catalog.json', 'utf8'));
const TAXONOMY = JSON.parse(readFileSync('catalog/taxonomy.json', 'utf8'));
const PKG = JSON.parse(readFileSync('package.json', 'utf8'));

const NAME = 'azure-sql';
const DISPLAY = 'Azure SQL Agent Skills';
const REPO = 'https://github.com/microsoft/azure-sql-skills';
const HOMEPAGE = 'https://github.com/microsoft/azure-sql-skills';
const BANNER = 'GENERATED by scripts/generate.mjs from catalog/catalog.json. Do not edit by hand; the parity gate will fail.';

const check = process.argv.includes('--check');
const outputs = new Map();
const emit = (path, body) => outputs.set(path, body);

// ---------------------------------------------------------------------------
// What actually exists on disk. Manifests must never advertise a skill with no
// content: an install that resolves nothing is the failure mode this project
// keeps guarding against.
// ---------------------------------------------------------------------------
// skills/ is FLAT, per the Agent Plugins specification, which discovers skills
// only as immediate children and forbids recursion. The domain comes from the
// sidecar, and the grouping below is generated from it.
const present = [];
if (existsSync('skills')) {
  for (const name of readdirSync('skills').filter((d) => statSync(join('skills', d)).isDirectory())) {
    if (!existsSync(join('skills', name, 'SKILL.md'))) continue;
    const sidecar = join('skills', name, 'skill.spec.jsonc');
    const domain = existsSync(sidecar)
      ? JSON.parse(readFileSync(sidecar, 'utf8').replace(/^\s*\/\/.*$/gm, '')).domain
      : undefined;
    present.push({ domain, name });
  }
}
present.sort((a, b) => a.name.localeCompare(b.name));

const description = (name) => {
  const text = readFileSync(join('skills', name, 'SKILL.md'), 'utf8');
  const end = text.indexOf('\n---', 4);
  const fm = text.slice(4, end);
  const m = /^description:\s*(.*)$/m.exec(fm);
  if (!m) return '';
  if (m[1] === '>-' || m[1] === '>' || m[1] === '|') {
    const after = fm.slice(fm.indexOf(m[0]) + m[0].length);
    return after.split('\n').filter((l) => /^\s+\S/.test(l)).map((l) => l.trim()).join(' ');
  }
  return m[1].replace(/^["']|["']$/g, '');
};

const byId = Object.fromEntries(CATALOG.skills.map((s) => [s.id, s]));
const domainOf = Object.fromEntries(TAXONOMY.domains.map((d) => [d.slug, d]));

// Skill paths, explicit rather than a directory. Prior art points at a FLAT
// skills/ directory; ours is skills/<domain>/<skill>/, and whether a loader
// recurses into a second level is not documented for every target. Naming each
// skill removes the question.
// Claude Code is the one target outside the Agent Plugins standard, so it keeps
// its own marketplace format and its own enumerated skill paths.
const skillPaths = present.map((p) => `./skills/${p.name}`);

const KEYWORDS = ['azure-sql', 'sql', 'database', 'tsql', 'agent-skills', 'vector-search', 'entra-id'];
const SUMMARY =
  'Agent skills for Azure SQL Database. They teach a coding agent what it otherwise gets wrong, ' +
  'usually because it learned SQL from PostgreSQL or from documentation written before Azure existed.';

// ---------------------------------------------------------------------------
// llms.txt, per the llmstxt.org convention: a title, a summary, then sections
// of links an agent can fetch.
// ---------------------------------------------------------------------------
{
  const lines = [`# ${DISPLAY}`, '', `> ${SUMMARY}`, '', `<!-- ${BANNER} -->`, ''];
  lines.push(
    'Every skill is a directory containing SKILL.md. The domain segment in the path is a source',
    'convention and is stripped on install, so an installed skill lands one level deep.',
    ''
  );
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    lines.push(`## ${d.title}`, '', `${d.goal}`, '');
    for (const p of here) {
      lines.push(`- [${p.name}](${REPO}/blob/main/skills/${p.name}/SKILL.md): ${description(p.name)}`);
    }
    lines.push('');
  }
  const planned = CATALOG.skills.filter((s) => !present.some((p) => p.name === s.id));
  lines.push('## Planned', '', `${planned.length} further skills are in the catalog and not yet written. They are listed with`,
    'their domain, wave and intent in catalog/catalog.json.', '');
  emit('llms.txt', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// README catalog table, written into a marked region so the prose around it
// stays hand-written.
// ---------------------------------------------------------------------------
{
  const rows = ['<!-- BEGIN GENERATED CATALOG -->', `<!-- ${BANNER} -->`, '',
    '| Domain | Skills | Wave 1 | Shipped |', '|---|---:|---:|---:|'];
  for (const d of TAXONOMY.domains) {
    const all = CATALOG.skills.filter((s) => s.domain === d.slug);
    const w1 = all.filter((s) => s.wave === 1).length;
    const on = present.filter((p) => p.domain === d.slug).length;
    rows.push(`| ${d.title} | ${all.length} | ${w1} | ${on} |`);
  }
  const total = CATALOG.skills.length;
  rows.push(`| **Total** | **${total}** | **${CATALOG.skills.filter((s) => s.wave === 1).length}** | **${present.length}** |`,
    '', '<!-- END GENERATED CATALOG -->');
  const readme = readFileSync('README.md', 'utf8');
  const begin = readme.indexOf('<!-- BEGIN GENERATED CATALOG -->');
  const end = readme.indexOf('<!-- END GENERATED CATALOG -->');
  if (begin < 0 || end < 0) {
    console.error('x README.md has no BEGIN/END GENERATED CATALOG markers');
    process.exit(1);
  }
  emit('README.md', readme.slice(0, begin) + rows.join('\n') + readme.slice(end + '<!-- END GENERATED CATALOG -->'.length));
}

// ---------------------------------------------------------------------------
// Plugin manifests. Shapes follow the pilot and microsoft/azure-skills, which
// are known-good, with skill paths enumerated because our layout is nested.
// ---------------------------------------------------------------------------
const base = {
  name: NAME,
  version: PKG.version,
  description: SUMMARY,
  author: { name: 'Microsoft', url: 'https://microsoft.com' },
  homepage: HOMEPAGE,
  repository: REPO,
  license: 'MIT',
  keywords: KEYWORDS,
};
const j = (o) => JSON.stringify({ $comment: BANNER, ...o }, null, 2) + '\n';

emit('.claude-plugin/plugin.json', j({ ...base, skills: skillPaths }));
emit('.claude-plugin/marketplace.json', j({
  name: NAME,
  owner: { name: 'Microsoft', url: REPO },
  metadata: { description: SUMMARY },
  // Wave 2 adds one entry per persona, each with its own skills array.
  plugins: [{ name: NAME, source: './', description: SUMMARY, version: PKG.version, skills: skillPaths }],
}));

// The Agent Plugins package IS the repository root: plugin.json beside a flat
// skills/. Nothing to generate into a subdirectory, and no per-vendor manifest
// for Codex, Cursor, Grok or the neutral schema, because every one of those is
// an Agent Plugins client and the portable package serves them all.
//
// plugin.json is generated here so its version and description cannot drift
// from package.json and the catalog.
emit('plugin.json', JSON.stringify({
  $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
  name: NAME,
  version: PKG.version,
  description: SUMMARY,
  author: { name: 'Microsoft', url: 'https://microsoft.com' },
  homepage: HOMEPAGE,
  repository: REPO,
  license: 'MIT',
  keywords: KEYWORDS,
}, null, 2) + '\n');

// ---------------------------------------------------------------------------
// apm.yml. APM authors skills flat under .apm/skills/ and installs whole
// packages, so this declares the package rather than a subset.
// ---------------------------------------------------------------------------
{
  const lines = [`# ${BANNER}`, '', 'version: 1', `name: ${NAME}`, `description: >-`, `  ${SUMMARY}`,
    `version_number: "${PKG.version}"`, `homepage: ${HOMEPAGE}`, `repository: ${REPO}`, 'license: MIT', '', 'skills:'];
  for (const p of present) lines.push(`  - ./skills/${p.domain}/${p.name}`);
  lines.push('');
  emit('apm.yml', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// Deliberately NOT generated: mcp.json.
//
// The plan calls for shipping a pointer to the SQL MCP endpoint beside the
// skills, the way microsoft/azure-skills ships .mcp.json. There is no endpoint
// to point at yet: the MCP server repository is not created for this milestone.
// Writing a plausible URL now would produce a manifest that looks correct and
// resolves to nothing, which is precisely the failure this repository keeps
// finding. It lands when the endpoint does.
// ---------------------------------------------------------------------------

let stale = 0;
for (const [path, body] of outputs) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === body) continue;
  stale++;
  if (check) {
    console.error(`x ${path} is out of date`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`  wrote ${path}`);
  }
}

if (check) {
  if (stale) {
    console.error(`\n${stale} generated file(s) differ from a fresh generation.`);
    console.error('Run "npm run generate" and commit the result. Do not edit generated files by hand.');
    process.exit(1);
  }
  console.log(`all ${outputs.size} generated surfaces are current`);
} else {
  console.log(`${outputs.size} surfaces generated, ${stale} changed, from ${present.length} skills on disk`);
}
