#!/usr/bin/env node
// Generate every derived surface from catalog/catalog.json and
// catalog/taxonomy.json. Nothing here is hand-edited, and CI proves it by
// regenerating and diffing.
//
//   node scripts/generate.mjs            write
//   node scripts/generate.mjs --check    fail if any output would change
//
// WHY THIS EXISTS: the pilot maintained llms.txt and four plugin manifests by
// hand. They drifted, and two repository-wide audits missed them because plugin
// manifests hide in dot-directories as .json. Generating them from one source
// makes drift a build failure instead of a discovery.

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';

const CATALOG = JSON.parse(readFileSync('catalog/catalog.json', 'utf8'));
const TAXONOMY = JSON.parse(readFileSync('catalog/taxonomy.json', 'utf8'));
const PKG = JSON.parse(readFileSync('package.json', 'utf8'));

const NAME = 'azure-sql';
const DISPLAY = 'Azure SQL Agent Skills';
const REPO = 'https://github.com/microsoft/azure-sql-skills';
const HOMEPAGE = 'https://github.com/microsoft/azure-sql-skills';
const BANNER = 'GENERATED by scripts/generate.mjs from catalog/catalog.json. Do not edit by hand; the parity gate will fail.';

const check = process.argv.includes('--check');
const outputs = new Map();
const emit = (path, body) => outputs.set(path, body);

// ---------------------------------------------------------------------------
// What actually exists on disk. Manifests must never advertise a skill with no
// content: an install that resolves nothing is the failure mode this project
// keeps guarding against.
// ---------------------------------------------------------------------------
// skills/ is FLAT, per the Agent Plugins specification, which discovers skills
// only as immediate children and forbids recursion. The domain comes from the
// sidecar, and the grouping below is generated from it.
const present = [];
if (existsSync('skills')) {
  for (const name of readdirSync('skills').filter((d) => statSync(join('skills', d)).isDirectory())) {
    if (!existsSync(join('skills', name, 'SKILL.md'))) continue;
    const sidecar = join('skills', name, 'skill.spec.jsonc');
    const domain = existsSync(sidecar)
      ? JSON.parse(readFileSync(sidecar, 'utf8').replace(/^\s*\/\/.*$/gm, '')).domain
      : undefined;
    present.push({ domain, name });
  }
}
present.sort((a, b) => a.name.localeCompare(b.name));

const description = (name) => {
  const text = readFileSync(join('skills', name, 'SKILL.md'), 'utf8');
  const end = text.indexOf('\n---', 4);
  const fm = text.slice(4, end);
  const m = /^description:\s*(.*)$/m.exec(fm);
  if (!m) return '';
  if (m[1] === '>-' || m[1] === '>' || m[1] === '|') {
    const after = fm.slice(fm.indexOf(m[0]) + m[0].length);
    return after.split('\n').filter((l) => /^\s+\S/.test(l)).map((l) => l.trim()).join(' ');
  }
  return m[1].replace(/^["']|["']$/g, '');
};

const byId = Object.fromEntries(CATALOG.skills.map((s) => [s.id, s]));
const domainOf = Object.fromEntries(TAXONOMY.domains.map((d) => [d.slug, d]));

// Skill paths, explicit rather than a directory. Prior art points at a FLAT
// skills/ directory; ours is flat, skills/<skill>/, and whether a loader
// recurses into a second level is not documented for every target. Naming each
// skill removes the question.
// Claude Code is the one target outside the Agent Plugins standard, so it keeps
// its own marketplace format and its own enumerated skill paths.
const skillPaths = present.map((p) => `./skills/${p.name}`);

const KEYWORDS = ['azure-sql', 'sql', 'database', 'tsql', 'agent-skills', 'vector-search', 'entra-id'];
// The single public-facing pitch. It reaches llms.txt, apm.yml, plugin.json,
// .claude-plugin/plugin.json and BOTH description fields in
// .claude-plugin/marketplace.json, which is the file that goes out to the
// marketplaces. One string so the pitch cannot drift between them, and the
// parity gate keeps it that way.
//
// Front-load it. A marketplace listing shows the detail view in full but a grid
// row can be cut to the terminal width, so the first sixty characters have to
// carry the point on their own.
//
// What it must not do: open with a category noun. The line this replaced spent
// its whole budget explaining WHY an agent is wrong, about PostgreSQL and old
// documentation, and never said what a reader gets. It also led with "Agent
// skills for Azure SQL Database", which tells a browser the shelf it is already
// standing in front of.
//
// No skill count. Carlos, 2026-09-01: a number is not value. Provenance is.
const SUMMARY =
  'Curated by the Azure SQL Database product team. Skills that correct what coding agents get ' +
  'wrong about the engine, from connection strings to vector search, measured against a live ' +
  'database rather than quoted from documentation.';

// ---------------------------------------------------------------------------
// llms.txt, per the llmstxt.org convention: a title, a summary, then sections
// of links an agent can fetch.
// ---------------------------------------------------------------------------
{
  const lines = [`# ${DISPLAY}`, '', `> ${SUMMARY}`, '', `<!-- ${BANNER} -->`, ''];
  lines.push(
    'Every skill is an immediate child of skills/, containing SKILL.md. The layout is flat because',
    'the Agent Plugins specification fixes discovery at skills/ and forbids a conforming client from',
    'searching deeper. Domain is metadata in the sidecar, not a directory.',
    ''
  );
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    lines.push(`## ${d.title}`, '', `${d.goal}`, '');
    for (const p of here) {
      lines.push(`- [${p.name}](${REPO}/blob/main/skills/${p.name}/SKILL.md): ${description(p.name)}`);
    }
    lines.push('');
  }
  const planned = CATALOG.skills.filter((s) => !present.some((p) => p.name === s.id));
  lines.push('## Planned', '', `${planned.length} further skills are in the catalog and not yet written. They are listed with`,
    'their domain, wave and intent in catalog/catalog.json.', '');
  emit('llms.txt', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// README catalog table, written into a marked region so the prose around it
// stays hand-written.
// ---------------------------------------------------------------------------
{
  // One entry per skill that exists, grouped by domain and collapsed, so the
  // list stays scannable as the catalog grows. A count table told a reader
  // nothing about what any skill does.
  const first = (name) => {
    const d = description(name).replace(/\s+/g, ' ').trim();
    const cut = d.search(/\.\s/);
    return cut > 0 ? d.slice(0, cut + 1) : d;
  };
  const rows = ['<!-- BEGIN GENERATED CATALOG -->', `<!-- ${BANNER} -->`, ''];
  rows.push(`**${present.length} skills** are installed by the commands above. Expand a group to see what each one does.`, '');
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    rows.push('<details>', `<summary><strong>${d.title}</strong> (${here.length})</summary>`, '');
    for (const p of here) {
      rows.push(`**[${p.name}](skills/${p.name}/SKILL.md)**`, '', first(p.name), '');
    }
    rows.push('</details>', '');
  }
  const planned = CATALOG.skills.length - present.length;
  rows.push(`A further ${planned} skills are planned. The full list, with the domain and intent of each, is in [catalog/catalog.json](catalog/catalog.json).`,
    '', '<!-- END GENERATED CATALOG -->');
  const readme = readFileSync('README.md', 'utf8');
  const begin = readme.indexOf('<!-- BEGIN GENERATED CATALOG -->');
  const end = readme.indexOf('<!-- END GENERATED CATALOG -->');
  if (begin < 0 || end < 0) {
    console.error('x README.md has no BEGIN/END GENERATED CATALOG markers');
    process.exit(1);
  }
  emit('README.md', readme.slice(0, begin) + rows.join('\n') + readme.slice(end + '<!-- END GENERATED CATALOG -->'.length));
}

// ---------------------------------------------------------------------------
// The feedback issue form's skill dropdown. Only the options list is
// generated, inside a marked region, the same split as the README table:
// the surrounding form (field ids, labels, other dropdowns) stays hand
// authored, because scripts/check-prefill-contract.mjs pins those ids and a
// skill fills the form by them.
//
// Grouped by domain because GitHub issue forms have no native optgroup: a
// quoted "-- Domain title --" line is a real, selectable option, but it reads
// as a heading and nothing downstream depends on its value. The two catch-all
// options are appended last and their text is a stable contract in its own
// right: the skill-feedback skill's prefill logic falls back to "Not sure"
// when a skill id is not in this list, so that string cannot change here
// without changing the skill in the lab too.
// ---------------------------------------------------------------------------
{
  const FORM = '.github/ISSUE_TEMPLATE/skill_feedback.yml';
  const INDENT = '        ';
  const BEGIN = `${INDENT}# BEGIN GENERATED SKILL OPTIONS`;
  const END = `${INDENT}# END GENERATED SKILL OPTIONS`;
  const lines = [BEGIN, `${INDENT}# ${BANNER}`];
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    lines.push(`${INDENT}- "-- ${d.title} --"`);
    for (const p of here) lines.push(`${INDENT}- ${p.name}`);
  }
  lines.push(`${INDENT}- The collection as a whole (install, discovery, or the wrong skill loaded)`);
  lines.push(`${INDENT}- Not sure`);
  lines.push(END);
  const text = readFileSync(FORM, 'utf8');
  const begin = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (begin < 0 || end < 0) {
    console.error(`x ${FORM} has no BEGIN/END GENERATED SKILL OPTIONS markers`);
    process.exit(1);
  }
  emit(FORM, text.slice(0, begin) + lines.join('\n') + text.slice(end + END.length));
}

// ---------------------------------------------------------------------------
// Plugin manifests.
//
// WHERE THE SKILL LIST BELONGS, and where it does not. Claude Code documents a
// `skills` field on both files, and it behaves differently in each:
//
//   plugin.json       "Adds to the default skills/ scan". Our skills ARE in
//                     skills/, so enumerating them here listed 56 paths that
//                     were already found. Removed 2026-09-02.
//
//   marketplace.json  For an entry whose source resolves to the marketplace
//                     root, which "./" does, declaring subdirectories REPLACES
//                     the default scan. The list there is load bearing, so it
//                     stays.
//
// The sentence this replaced said the paths were enumerated "because our layout
// is nested". It is not nested. Line 36 pins skills/ flat and all 56 sit at
// skills/<name>/SKILL.md. That sentence sent a reader hunting a problem that did
// not exist.
// ---------------------------------------------------------------------------
const base = {
  name: NAME,
  version: PKG.version,
  description: SUMMARY,
  author: { name: 'Microsoft', url: 'https://microsoft.com' },
  homepage: HOMEPAGE,
  repository: REPO,
  license: 'MIT',
  keywords: KEYWORDS,
};
const j = (o) => JSON.stringify({ $comment: BANNER, ...o }, null, 2) + '\n';

// DISPLAY NAME. Every storefront that has one renders `azure-sql` raw, and
// Cursor title-cases it into "Azure Sql", which is nobody's brand. Carlos chose
// "Azure SQL" for the collection on 2026-09-02: the family brand rather than
// "Azure SQL Database", because this is 56 skills across the family and not one
// product.
//
// It cannot go in the portable plugin.json. That schema is
// additionalProperties:false with no displayName, so adding one would make the
// file invalid for every conformant client. It belongs in the per-tool
// manifests, which is the whole reason those exist.
// NOT the same as DISPLAY above, which titles llms.txt as "Azure SQL Agent
// Skills". This is what a storefront shows beside the install button, and
// Carlos chose it on 2026-09-02: the family brand, because this is 56 skills
// across the family rather than one product. Two surfaces, two names, said
// once each.
const STORE_NAME = 'Azure SQL';

emit('.claude-plugin/plugin.json', j({ displayName: STORE_NAME, ...base }));

// ---------------------------------------------------------------------------
// EXPERIMENTAL, 2026-09-21: scoped collections from ONE skills tree.
//
// The question this answers is whether several marketplace entries can share a
// single copy of skills/ and each carry a different subset, with no file
// copying. Claude Code documents that for an entry whose `source` resolves to
// the marketplace root, a `skills` array REPLACES the default scan, so the
// entry loads exactly the listed paths. Every entry below therefore keeps
// `source: "./"` and differs only in its list.
//
// The Agent Plugins specification takes the other position: discovery is fixed
// at skills/ and a manifest cannot override it. A client that follows the
// specification rather than the Claude Code reading will load all 57 into every
// entry. Which clients do which is measured per client, not assumed here.
//
// The two entries below are EXPERIMENTAL and must not ship without that
// measurement. The everything entry is unchanged and stays first.
//
// Data API builder skills are excluded from the Visual Studio Code collection
// because they clash with Data API builder tooling already present in GitHub
// Copilot inside the MSSQL extension for Visual Studio Code.
// ---------------------------------------------------------------------------
const DAB_SKILLS = ['dab-rest-and-graphql', 'azuresql-db-dab'];
const pathsWhere = (keep) => present.filter((p) => keep(p.name)).map((p) => `./skills/${p.name}`);

const vscodeSkills = pathsWhere((n) => !DAB_SKILLS.includes(n));
const containerSkills = pathsWhere((n) => n.startsWith('azuresql-db-'));

// Fail loudly rather than emit a silently empty or unfiltered collection: an
// entry that resolves to nothing, or to everything, is the failure mode this
// repository keeps finding late.
for (const [label, list, expected] of [
  ['vscode', vscodeSkills, present.length - DAB_SKILLS.length],
  ['container', containerSkills, 17],
]) {
  if (list.length !== expected) {
    console.error(`x the ${label} collection resolved ${list.length} skills, expected ${expected}`);
    process.exit(1);
  }
}

emit('.claude-plugin/marketplace.json', j({
  name: NAME,
  owner: { name: 'Microsoft', url: REPO },
  metadata: { description: SUMMARY },
  plugins: [
    { name: NAME, source: './', description: SUMMARY, version: PKG.version, skills: skillPaths },
    {
      name: `${NAME}-vscode`,
      source: './',
      description:
        'EXPERIMENTAL. The collection without the Data API builder skills, for the MSSQL extension ' +
        'for Visual Studio Code, where GitHub Copilot already carries Data API builder tooling.',
      version: PKG.version,
      skills: vscodeSkills,
    },
    {
      name: `${NAME}-container`,
      source: './',
      description:
        'EXPERIMENTAL. The Azure SQL Database container skills only, for local development against ' +
        'the container rather than a provisioned database.',
      version: PKG.version,
      skills: containerSkills,
    },
  ],
}));

// PER-TOOL MANIFESTS, and why there are now two of them.
//
// Every one of these tools already loads us from the portable plugin.json,
// proved by installing into five of them on 2026-09-02. These files add nothing
// to compatibility. They exist for one reason: the portable schema carries no
// display name, so without them each storefront shows `azure-sql`.
//
// Generated, never hand-written. azure-sql-database-container keeps four of
// these by hand and they have already drifted: two spell the skills path
// differently and only one carries a logo. Generating them from one source is
// the difference between a display name and a maintenance problem.
//
// WHERE A LOGO CAN GO, checked against each tool's own schema:
//
//   Cursor        `logo`, documented, and VERIFIED RENDERING on 2026-09-02
//   Codex         interface.logo and interface.composerIcon, documented
//   Claude Code   NO image field of any kind in its plugin manifest schema
//   plugin.json   NO image field. The portable schema is closed
//
// So the mark reaches two of four storefronts, and no manifest change reaches
// the other two.
//
//   Codex   documents interface.displayName, and skills as a string path
//
//   Cursor  MEASURED 2026-09-02, and the bet lost. Cursor does not document
//           displayName and does not honour it. Installed
//           azure-sql-database-container, whose manifest asks for "Azure SQL
//           Database container", and Cursor's panel rendered "Azure Sql
//           Database Container": title-cased from `name`, ignoring the field.
//           So displayName stays here because it costs nothing and may be
//           honoured later, and this comment exists so nobody reads its
//           presence as evidence that it works. In Cursor we are "Azure Sql".
//
//           `logo` IS documented and DOES work: the same install rendered the
//           container repo's SVG in the panel. Hence assets/plugin-logo.svg,
//           byte-identical to the container repo's, so the family looks like
//           one family..
emit('.codex-plugin/plugin.json', j({
  ...base,
  skills: './skills/',
  interface: {
    displayName: STORE_NAME,
    shortDescription: SUMMARY,
    category: 'Databases',
    // Codex documents composerIcon, logo, logoDark and screenshots. We ship one
    // SVG for both light and dark: it is a flat Azure mark with its own
    // background, so it does not need a second variant, and inventing one we
    // never look at is how a second file goes stale.
    logo: 'assets/plugin-logo.svg',
    composerIcon: 'assets/plugin-logo.svg',
  },
}));
emit('.cursor-plugin/plugin.json', j({ displayName: STORE_NAME, ...base, skills: 'skills/', logo: 'assets/plugin-logo.svg' }));

// The Agent Plugins package IS the repository root: plugin.json beside a flat
// skills/. Nothing to generate into a subdirectory, and NO displayName here:
// that schema is closed and has no such field.
//
// plugin.json is generated here so its version and description cannot drift
// from package.json and the catalog.
emit('plugin.json', JSON.stringify({
  $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
  name: NAME,
  version: PKG.version,
  description: SUMMARY,
  author: { name: 'Microsoft', url: 'https://microsoft.com' },
  homepage: HOMEPAGE,
  repository: REPO,
  license: 'MIT',
  keywords: KEYWORDS,
}, null, 2) + '\n');

// ---------------------------------------------------------------------------
// apm.yml, the OpenAPM manifest.
//
// What was here before did not work, and nobody had run the tool to find out.
// It declared `version: 1`, which OpenAPM requires to be a SemVer string, put
// the real version in `version_number`, which is not a field, and listed
// `skills:` at the top level, which is not a field either. With no `targets:`,
// no `dependencies:` and no `marketplace:` block, `apm pack` reported "nothing
// to pack" and `apm targets` resolved all nine runtimes inactive. A generated,
// committed, public manifest that supported nothing.
//
// The comment it replaced said APM authors skills flat under `.apm/skills/`.
// That is one of two layouts APM accepts, and choosing it here would be a
// serious mistake: APM resolves `.apm/` IN PREFERENCE TO root-level `skills/`,
// so creating it would shadow the fixed directory the Agent Plugins
// specification pins, and every non-APM client would stop finding our skills
// with no error anywhere. We stay on the root layout, permanently, and APM
// reads it as a "Plugin collection" with no structural change.
//
// `targets:` is what makes `apm pack` emit anything. Skills are discovered from
// the root `skills/` directory rather than declared here, which is why there is
// no `skills:` key: the OpenAPM schema has none, and the root plugin.json
// cannot carry one either, because the Agent Plugins schema is closed and
// defines neither `skills` nor `agent`.
// ---------------------------------------------------------------------------
{
  const lines = [
    `# ${BANNER}`, '',
    `name: ${NAME}`,
    `version: "${PKG.version}"`,
    'description: >-', `  ${SUMMARY}`,
    'author: Microsoft',
    'license: MIT',
    `homepage: ${HOMEPAGE}`,
    `repository: ${REPO}`,
    'keywords: [' + KEYWORDS.join(', ') + ']',
    '',
    '# Constrains what this package may contain. Skills, and nothing else.',
    'type: skill',
    '',
    '# The runtimes `apm pack` emits plugin manifests for. Without this, pack',
    '# produces nothing, which is the state this file shipped in until 2026-09-01.',
    'targets:',
    '  - claude',
    '  - copilot',
    '',
  ];
  emit('apm.yml', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// Deliberately NOT generated: mcp.json.
//
// The plan calls for shipping a pointer to the SQL MCP endpoint beside the
// skills, the way microsoft/azure-skills ships .mcp.json. There is no endpoint
// to point at yet: the MCP server repository is not created for this milestone.
// Writing a plausible URL now would produce a manifest that looks correct and
// resolves to nothing, which is precisely the failure this repository keeps
// finding. It lands when the endpoint does.
// ---------------------------------------------------------------------------

let stale = 0;
for (const [path, body] of outputs) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === body) continue;
  stale++;
  if (check) {
    console.error(`x ${path} is out of date`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`  wrote ${path}`);
  }
}

if (check) {
  if (stale) {
    console.error(`\n${stale} generated file(s) differ from a fresh generation.`);
    console.error('Run "npm run generate" and commit the result. Do not edit generated files by hand.');
    process.exit(1);
  }
  console.log(`all ${outputs.size} generated surfaces are current`);
} else {
  console.log(`${outputs.size} surfaces generated, ${stale} changed, from ${present.length} skills on disk`);
}
