#!/usr/bin/env node
// Generate every derived surface from catalog/catalog.json and
// catalog/taxonomy.json. Nothing here is hand-edited, and CI proves it by
// regenerating and diffing.
//
//   node scripts/generate.mjs            write
//   node scripts/generate.mjs --check    fail if any output would change
//
// WHY THIS EXISTS: the pilot maintained llms.txt and four plugin manifests by
// hand. They drifted, and two repository-wide audits missed them because plugin
// manifests hide in dot-directories as .json. Generating them from one source
// makes drift a build failure instead of a discovery.

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync, rmSync, cpSync } from 'node:fs';
import { join, dirname } from 'node:path';

const CATALOG = JSON.parse(readFileSync('catalog/catalog.json', 'utf8'));
const TAXONOMY = JSON.parse(readFileSync('catalog/taxonomy.json', 'utf8'));
const SCOPED = JSON.parse(readFileSync('catalog/plugins.json', 'utf8')).plugins;
const PKG = JSON.parse(readFileSync('package.json', 'utf8'));

// Two names, because an install reads `<plugin>@<marketplace>` and Carlos chose
// `microsoft-sql@microsoft-sql` on 2026-09-21: the plugin takes the repository name,
// which Codex also requires, since it refuses an entry whose plugin.json name differs
// from the marketplace entry name. The plugin name is the stable id that
// settings and install commands reference. The marketplace name is what
// `marketplace add` registers the repository as.
const PLUGIN_NAME = 'microsoft-sql';
const MARKETPLACE_NAME = 'microsoft-sql';
const DISPLAY = 'Microsoft SQL';
// The publisher name every manifest shows beside the version. Carlos, 2026-09-18.
const AUTHOR = 'Microsoft SQL';
// The repository is being renamed to microsoft/microsoft-sql. These links do not
// resolve until it is, so this lands right after the rename.
const REPO = 'https://github.com/microsoft/microsoft-sql';
const HOMEPAGE = 'https://github.com/microsoft/microsoft-sql';
const BANNER = 'GENERATED by scripts/generate.mjs from catalog/catalog.json. Do not edit by hand; the parity gate will fail.';

const check = process.argv.includes('--check');
const outputs = new Map();
const emit = (path, body) => outputs.set(path, body);

// ---------------------------------------------------------------------------
// What actually exists on disk. Manifests must never advertise a skill with no
// content: an install that resolves nothing is the failure mode this project
// keeps guarding against.
// ---------------------------------------------------------------------------
// skills/ is FLAT, per the Agent Plugins specification, which discovers skills
// only as immediate children and forbids recursion. The domain comes from the
// sidecar, and the grouping below is generated from it.
const present = [];
if (existsSync('skills')) {
  for (const name of readdirSync('skills').filter((d) => statSync(join('skills', d)).isDirectory())) {
    if (!existsSync(join('skills', name, 'SKILL.md'))) continue;
    const sidecar = join('skills', name, 'skill.spec.jsonc');
    const domain = existsSync(sidecar)
      ? JSON.parse(readFileSync(sidecar, 'utf8').replace(/^\s*\/\/.*$/gm, '')).domain
      : undefined;
    present.push({ domain, name });
  }
}
present.sort((a, b) => a.name.localeCompare(b.name));

const description = (name) => {
  const text = readFileSync(join('skills', name, 'SKILL.md'), 'utf8');
  const end = text.indexOf('\n---', 4);
  const fm = text.slice(4, end);
  const m = /^description:\s*(.*)$/m.exec(fm);
  if (!m) return '';
  if (m[1] === '>-' || m[1] === '>' || m[1] === '|') {
    const after = fm.slice(fm.indexOf(m[0]) + m[0].length);
    return after.split('\n').filter((l) => /^\s+\S/.test(l)).map((l) => l.trim()).join(' ');
  }
  return m[1].replace(/^["']|["']$/g, '');
};

const byId = Object.fromEntries(CATALOG.skills.map((s) => [s.id, s]));
const domainOf = Object.fromEntries(TAXONOMY.domains.map((d) => [d.slug, d]));

// Skill paths, explicit rather than a directory. Prior art points at a FLAT
// skills/ directory; ours is flat, skills/<skill>/, and whether a loader
// recurses into a second level is not documented for every target. Naming each
// skill removes the question.
// Claude Code is the one target outside the Agent Plugins standard, so it keeps
// its own marketplace format and its own enumerated skill paths.
const skillPaths = present.map((p) => `./skills/${p.name}`);

// ---------------------------------------------------------------------------
// SCOPED PLUGINS. One folder per surface under plugins/, each carrying byte
// copies of the skills catalog/plugins.json lists for it.
//
// WHY COPIES AND NOT A SKILL LIST IN A MANIFEST. Measured on 2026-09-21 across
// four clients, twice:
//
//   entries at source "./" with their own `skills` array
//     Claude Code honoured it. GitHub Copilot CLI printed a filtered count and
//     then loaded all 57 under every entry. Cursor ignored the list. Codex
//     refused the install outright, because a marketplace entry name must match
//     the name inside that plugin's own plugin.json.
//
//   real folders holding symlinks back to skills/
//     Claude Code and GitHub Copilot CLI correct. CODEX LOADED ZERO: it reports
//     "Added plugin" and leaves an empty skills directory in its cache, with no
//     error anywhere. Out on Windows too, where a clone with core.symlinks=false
//     writes each link as a small text file holding the path.
//
//   real folders holding copies
//     Claude Code, GitHub Copilot CLI, Codex and Cursor all load exactly the
//     subset. This is why the content exists more than once on disk, and why
//     there is still exactly one place a human edits it: skills/.
//
// The Agent Plugins specification does not describe a repository holding several
// plugins, and has no marketplace concept at all. It describes one plugin as one
// directory with plugin.json at its root and a fixed skills/ scan beneath it.
// Each folder under plugins/ is therefore a conformant plugin in its own right,
// and the per-client marketplace files are what tie them together.
// ---------------------------------------------------------------------------
const onDisk = new Set(present.map((p) => p.name));
const fail = (msg) => { console.error(`x ${msg}`); process.exit(1); };
for (const s of SCOPED) {
  if (!/^[a-z0-9-]+$/.test(s.name)) fail(`plugin name "${s.name}" is not a lowercase slug`);
  if (!s.skills.length) fail(`${s.name} lists no skills, so it would install nothing`);
  const missing = s.skills.filter((id) => !onDisk.has(id));
  if (missing.length) fail(`${s.name} lists ${missing.length} skill(s) with no content in skills/: ${missing.join(', ')}`);
  const twice = s.skills.filter((id, i) => s.skills.indexOf(id) !== i);
  if (twice.length) fail(`${s.name} lists ${twice.join(', ')} more than once`);
  const banned = s.skills.filter((id) => (s.mustNotInclude ?? []).includes(id));
  if (banned.length) fail(`${s.name} carries ${banned.join(', ')}, which its own mustNotInclude forbids`);
}

const KEYWORDS = ['microsoft-sql', 'azure-sql', 'sql', 'database', 'tsql', 'agent-skills', 'vector-search', 'entra-id'];
// The single public-facing pitch. It reaches llms.txt, apm.yml, plugin.json,
// .claude-plugin/plugin.json and BOTH description fields in
// .claude-plugin/marketplace.json, which is the file that goes out to the
// marketplaces. One string so the pitch cannot drift between them, and the
// parity gate keeps it that way.
//
// Front-load it. A marketplace listing shows the detail view in full but a grid
// row can be cut to the terminal width, so the first sixty characters have to
// carry the point on their own.
//
// What it must not do: open with a category noun. The line this replaced spent
// its whole budget explaining WHY an agent is wrong, about PostgreSQL and old
// documentation, and never said what a reader gets. It also led with "Agent
// skills for Azure SQL Database", which tells a browser the shelf it is already
// standing in front of.
//
// No skill count. Carlos, 2026-09-01: a number is not value. Provenance is.
// Leads with the plugin's name, Microsoft SQL, since 2026-09-18. No "skills" in
// the name: the plugin will carry an MCP server too.
const SUMMARY =
  'From the Microsoft SQL product team. Build AI-ready apps on Azure SQL Database with vector ' +
  'search, RAG, REST APIs, serverless functions, passwordless auth, and the ORMs you already use.';

// ---------------------------------------------------------------------------
// llms.txt, per the llmstxt.org convention: a title, a summary, then sections
// of links an agent can fetch.
// ---------------------------------------------------------------------------
{
  const lines = [`# ${DISPLAY}`, '', `> ${SUMMARY}`, '', `<!-- ${BANNER} -->`, ''];
  lines.push(
    'Every skill is an immediate child of skills/, containing SKILL.md. The layout is flat because',
    'the Agent Plugins specification fixes discovery at skills/ and forbids a conforming client from',
    'searching deeper. Domain is metadata in the sidecar, not a directory.',
    ''
  );
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    lines.push(`## ${d.title}`, '', `${d.goal}`, '');
    for (const p of here) {
      lines.push(`- [${p.name}](${REPO}/blob/main/skills/${p.name}/SKILL.md): ${description(p.name)}`);
    }
    lines.push('');
  }
  const planned = CATALOG.skills.filter((s) => !present.some((p) => p.name === s.id));
  lines.push('## Planned', '', `${planned.length} further skills are in the catalog and not yet written. They are listed with`,
    'their domain, wave and intent in catalog/catalog.json.', '');
  emit('llms.txt', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// README catalog table, written into a marked region so the prose around it
// stays hand-written.
// ---------------------------------------------------------------------------
{
  // One entry per skill that exists, grouped by domain and collapsed, so the
  // list stays scannable as the catalog grows. A count table told a reader
  // nothing about what any skill does.
  const first = (name) => {
    const d = description(name).replace(/\s+/g, ' ').trim();
    const cut = d.search(/\.\s/);
    return cut > 0 ? d.slice(0, cut + 1) : d;
  };
  const rows = ['<!-- BEGIN GENERATED CATALOG -->', `<!-- ${BANNER} -->`, ''];
  rows.push(`**${present.length} skills** are installed by the commands above. Expand a group to see what each one does.`, '');
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    rows.push('<details>', `<summary><strong>${d.title}</strong> (${here.length})</summary>`, '');
    for (const p of here) {
      rows.push(`**[${p.name}](skills/${p.name}/SKILL.md)**`, '', first(p.name), '');
    }
    rows.push('</details>', '');
  }
  const planned = CATALOG.skills.length - present.length;
  rows.push(`A further ${planned} skills are planned. The full list, with the domain and intent of each, is in [catalog/catalog.json](catalog/catalog.json).`,
    '', '<!-- END GENERATED CATALOG -->');
  const readme = readFileSync('README.md', 'utf8');
  const begin = readme.indexOf('<!-- BEGIN GENERATED CATALOG -->');
  const end = readme.indexOf('<!-- END GENERATED CATALOG -->');
  if (begin < 0 || end < 0) {
    console.error('x README.md has no BEGIN/END GENERATED CATALOG markers');
    process.exit(1);
  }
  emit('README.md', readme.slice(0, begin) + rows.join('\n') + readme.slice(end + '<!-- END GENERATED CATALOG -->'.length));
}

// ---------------------------------------------------------------------------
// The feedback issue form's skill dropdown. Only the options list is
// generated, inside a marked region, the same split as the README table:
// the surrounding form (field ids, labels, other dropdowns) stays hand
// authored, because scripts/check-prefill-contract.mjs pins those ids and a
// skill fills the form by them.
//
// Grouped by domain because GitHub issue forms have no native optgroup: a
// quoted "-- Domain title --" line is a real, selectable option, but it reads
// as a heading and nothing downstream depends on its value. The two catch-all
// options are appended last and their text is a stable contract in its own
// right: the skill-feedback skill's prefill logic falls back to "Not sure"
// when a skill id is not in this list, so that string cannot change here
// without changing the skill in the lab too.
// ---------------------------------------------------------------------------
{
  const FORM = '.github/ISSUE_TEMPLATE/skill_feedback.yml';
  const INDENT = '        ';
  const BEGIN = `${INDENT}# BEGIN GENERATED SKILL OPTIONS`;
  const END = `${INDENT}# END GENERATED SKILL OPTIONS`;
  const lines = [BEGIN, `${INDENT}# ${BANNER}`];
  for (const d of TAXONOMY.domains) {
    const here = present.filter((p) => p.domain === d.slug);
    if (here.length === 0) continue;
    lines.push(`${INDENT}- "-- ${d.title} --"`);
    for (const p of here) lines.push(`${INDENT}- ${p.name}`);
  }
  lines.push(`${INDENT}- The collection as a whole (install, discovery, or the wrong skill loaded)`);
  lines.push(`${INDENT}- Not sure`);
  lines.push(END);
  const text = readFileSync(FORM, 'utf8');
  const begin = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (begin < 0 || end < 0) {
    console.error(`x ${FORM} has no BEGIN/END GENERATED SKILL OPTIONS markers`);
    process.exit(1);
  }
  emit(FORM, text.slice(0, begin) + lines.join('\n') + text.slice(end + END.length));
}

// ---------------------------------------------------------------------------
// Plugin manifests.
//
// WHERE THE SKILL LIST BELONGS, and where it does not. Claude Code documents a
// `skills` field on both files, and it behaves differently in each:
//
//   plugin.json       "Adds to the default skills/ scan". Our skills ARE in
//                     skills/, so enumerating them here listed 56 paths that
//                     were already found. Removed 2026-09-02.
//
//   marketplace.json  For an entry whose source resolves to the marketplace
//                     root, which "./" does, declaring subdirectories REPLACES
//                     the default scan. The list there is load bearing, so it
//                     stays.
//
// The sentence this replaced said the paths were enumerated "because our layout
// is nested". It is not nested. Line 36 pins skills/ flat and all 56 sit at
// skills/<name>/SKILL.md. That sentence sent a reader hunting a problem that did
// not exist.
// ---------------------------------------------------------------------------
const base = {
  name: PLUGIN_NAME,
  version: PKG.version,
  description: SUMMARY,
  author: { name: AUTHOR, url: 'https://microsoft.com' },
  homepage: HOMEPAGE,
  repository: REPO,
  license: 'MIT',
  keywords: KEYWORDS,
};
const j = (o) => JSON.stringify({ $comment: BANNER, ...o }, null, 2) + '\n';

// DISPLAY NAME. What a storefront shows beside the install button. Carlos chose
// "Microsoft SQL" on 2026-09-18, replacing "Azure SQL" from 2026-09-02.
//
// It cannot go in the portable plugin.json. That schema is
// additionalProperties:false with no displayName, so adding one would make the
// file invalid for every conformant client. It belongs in the per-tool
// manifests, which is the whole reason those exist. A client that reads only
// the portable manifest, VS Code among them, shows PLUGIN_NAME instead.
//
// NOT the same as DISPLAY above, which titles llms.txt. Two surfaces, two
// names, said once each.
//
// Claude Code documents displayName on BOTH plugin.json and the marketplace
// entry, falling back to `name` when omitted, so it goes in both.
const STORE_NAME = 'Microsoft SQL';

emit('.claude-plugin/plugin.json', j({ displayName: STORE_NAME, ...base }));
emit('.claude-plugin/marketplace.json', j({
  name: MARKETPLACE_NAME,
  owner: { name: AUTHOR, url: REPO },
  metadata: { description: SUMMARY },
  plugins: [
    { name: PLUGIN_NAME, displayName: STORE_NAME, source: './', description: SUMMARY, version: PKG.version, skills: skillPaths },
    // The scoped plugins carry NO skills array. Their source is a real plugin
    // folder, so the default skills/ scan inside it is the whole declaration,
    // and that scan is the one thing all four clients agreed on.
    ...SCOPED.map((s) => ({
      name: s.name,
      displayName: s.displayName,
      source: `./plugins/${s.name}`,
      description: s.description,
      version: PKG.version,
    })),
  ],
}));

// PER-TOOL MANIFESTS, and why there are now two of them.
//
// Every one of these tools already loads us from the portable plugin.json,
// proved by installing into five of them on 2026-09-02. These files add nothing
// to compatibility. They exist for one reason: the portable schema carries no
// display name, so without them each storefront shows `azure-sql`.
//
// Generated, never hand-written. azure-sql-database-container keeps four of
// these by hand and they have already drifted: two spell the skills path
// differently and only one carries a logo. Generating them from one source is
// the difference between a display name and a maintenance problem.
//
// WHERE A LOGO CAN GO, checked against each tool's own schema:
//
//   Cursor        `logo`, documented, and VERIFIED RENDERING on 2026-09-02
//   Codex         interface.logo and interface.composerIcon, documented
//   Claude Code   NO image field of any kind in its plugin manifest schema
//   plugin.json   NO image field. The portable schema is closed
//
// So the mark reaches two of four storefronts, and no manifest change reaches
// the other two.
//
//   Codex   documents interface.displayName, and skills as a string path
//
//   Cursor  RE-MEASURED 2026-09-18, and it now honours displayName. On
//           2026-09-02 it ignored the field and title-cased `name`. Cursor
//           3.20.10 reads .cursor-plugin/plugin.json first, then
//           .claude-plugin/plugin.json, then plugin.json, and its panel showed
//           "Microsoft SQL" for this plugin imported from Claude Code. One
//           exception: a folder copied by hand into ~/.cursor/plugins/local is
//           labelled with the folder name, whatever the manifest says.
//
//           `logo` IS documented and DOES work: the same install rendered the
//           container repo's SVG in the panel. Hence assets/plugin-logo.svg,
//           byte-identical to the container repo's, so the family looks like
//           one family..
emit('.codex-plugin/plugin.json', j({
  ...base,
  skills: './skills/',
  interface: {
    displayName: STORE_NAME,
    shortDescription: SUMMARY,
    category: 'Databases',
    // Codex documents composerIcon, logo, logoDark and screenshots. We ship one
    // SVG for both light and dark: it is a flat Azure mark with its own
    // background, so it does not need a second variant, and inventing one we
    // never look at is how a second file goes stale.
    logo: 'assets/plugin-logo.svg',
    composerIcon: 'assets/plugin-logo.svg',
  },
}));
emit('.cursor-plugin/plugin.json', j({ displayName: STORE_NAME, ...base, skills: 'skills/', logo: 'assets/plugin-logo.svg' }));

// GROK. Grok Build registers a repository with `grok plugin marketplace add`
// and reads its index from .grok-plugin/marketplace.json, per its user guide
// (09-plugins.md), with a `{ type, path }` source object rather than Claude
// Code's bare "./". Restored 2026-09-18 so `grok plugin install microsoft`
// works; PR #9 removed the earlier Grok files on the grounds that Grok reads
// the portable package, which does not cover a marketplace install.
// NOT TESTED against a running Grok: none was installed when this was written.
emit('.grok-plugin/marketplace.json', j({
  name: MARKETPLACE_NAME,
  description: SUMMARY,
  owner: { name: AUTHOR, url: REPO },
  plugins: [
    { name: PLUGIN_NAME, displayName: STORE_NAME, description: SUMMARY, category: 'databases', source: { type: 'local', path: './' } },
    // Listed for the same reason as the Claude Code entries. UNMEASURED: no Grok
    // was installed when the scoped plugins were built, so this follows the
    // documented source shape rather than an observed install.
    ...SCOPED.map((s) => ({
      name: s.name,
      displayName: s.displayName,
      description: s.description,
      category: 'databases',
      source: { type: 'local', path: `./plugins/${s.name}` },
    })),
  ],
}));
emit('.grok-plugin/plugin.json', j({ displayName: STORE_NAME, ...base, skills: 'skills/' }));

// The Agent Plugins package IS the repository root: plugin.json beside a flat
// skills/. Nothing to generate into a subdirectory, and NO displayName here:
// that schema is closed and has no such field.
//
// plugin.json is generated here so its version and description cannot drift
// from package.json and the catalog.
emit('plugin.json', JSON.stringify({
  $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
  name: PLUGIN_NAME,
  version: PKG.version,
  description: SUMMARY,
  author: { name: AUTHOR, url: 'https://microsoft.com' },
  homepage: HOMEPAGE,
  repository: REPO,
  license: 'MIT',
  keywords: KEYWORDS,
}, null, 2) + '\n');

// ---------------------------------------------------------------------------
// The scoped plugins' own manifests. Four per folder, the same four the root
// carries, so a scoped plugin is installable by every client the root is.
//
// The logo is COPIED into each folder rather than referenced. Those paths are
// resolved relative to the plugin root, so a subfolder manifest pointing at
// assets/plugin-logo.svg at the repository root resolves to nothing.
//
// No per-plugin apm.yml: `apm pack` packages one project, and the root is it.
// ---------------------------------------------------------------------------
const LOGO = readFileSync('assets/plugin-logo.svg', 'utf8');
for (const s of SCOPED) {
  const dir = `plugins/${s.name}`;
  const sub = { ...base, name: s.name, description: s.description };
  emit(`${dir}/plugin.json`, JSON.stringify({
    $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
    name: s.name,
    version: PKG.version,
    description: s.description,
    author: { name: AUTHOR, url: 'https://microsoft.com' },
    homepage: HOMEPAGE,
    repository: REPO,
    license: 'MIT',
    keywords: KEYWORDS,
  }, null, 2) + '\n');
  emit(`${dir}/.claude-plugin/plugin.json`, j({ displayName: s.displayName, ...sub }));
  emit(`${dir}/.codex-plugin/plugin.json`, j({
    ...sub,
    skills: './skills/',
    interface: {
      displayName: s.displayName,
      shortDescription: s.description,
      category: 'Databases',
      logo: 'assets/plugin-logo.svg',
      composerIcon: 'assets/plugin-logo.svg',
    },
  }));
  emit(`${dir}/.cursor-plugin/plugin.json`, j({ displayName: s.displayName, ...sub, skills: 'skills/', logo: 'assets/plugin-logo.svg' }));
  emit(`${dir}/assets/plugin-logo.svg`, LOGO);
  emit(`${dir}/README.md`, [
    `# ${s.displayName}`,
    '',
    s.description,
    '',
    `Every file under this directory is GENERATED by scripts/generate.mjs from catalog/plugins.json`,
    `and skills/. Edit the skill in skills/ and run \`npm run generate\`. A copy edited here fails the`,
    'parity gate.',
    '',
    `Install it with \`${s.name}@${MARKETPLACE_NAME}\`. See the repository README for the commands your`,
    'client uses.',
    '',
  ].join('\n'));
}

// ---------------------------------------------------------------------------
// apm.yml, the OpenAPM manifest.
//
// What was here before did not work, and nobody had run the tool to find out.
// It declared `version: 1`, which OpenAPM requires to be a SemVer string, put
// the real version in `version_number`, which is not a field, and listed
// `skills:` at the top level, which is not a field either. With no `targets:`,
// no `dependencies:` and no `marketplace:` block, `apm pack` reported "nothing
// to pack" and `apm targets` resolved all nine runtimes inactive. A generated,
// committed, public manifest that supported nothing.
//
// The comment it replaced said APM authors skills flat under `.apm/skills/`.
// That is one of two layouts APM accepts, and choosing it here would be a
// serious mistake: APM resolves `.apm/` IN PREFERENCE TO root-level `skills/`,
// so creating it would shadow the fixed directory the Agent Plugins
// specification pins, and every non-APM client would stop finding our skills
// with no error anywhere. We stay on the root layout, permanently, and APM
// reads it as a "Plugin collection" with no structural change.
//
// `targets:` is what makes `apm pack` emit anything. Skills are discovered from
// the root `skills/` directory rather than declared here, which is why there is
// no `skills:` key: the OpenAPM schema has none, and the root plugin.json
// cannot carry one either, because the Agent Plugins schema is closed and
// defines neither `skills` nor `agent`.
// ---------------------------------------------------------------------------
{
  const lines = [
    `# ${BANNER}`, '',
    `name: ${PLUGIN_NAME}`,
    `version: "${PKG.version}"`,
    'description: >-', `  ${SUMMARY}`,
    `author: ${AUTHOR}`,
    'license: MIT',
    `homepage: ${HOMEPAGE}`,
    `repository: ${REPO}`,
    'keywords: [' + KEYWORDS.join(', ') + ']',
    '',
    '# Constrains what this package may contain. Skills, and nothing else.',
    'type: skill',
    '',
    '# The runtimes `apm pack` emits plugin manifests for. Without this, pack',
    '# produces nothing, which is the state this file shipped in until 2026-09-01.',
    'targets:',
    '  - claude',
    '  - copilot',
    '',
  ];
  emit('apm.yml', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// Deliberately NOT generated: mcp.json.
//
// The plan calls for shipping a pointer to the SQL MCP endpoint beside the
// skills, the way microsoft/azure-skills ships .mcp.json. There is no endpoint
// to point at yet: the MCP server repository is not created for this milestone.
// Writing a plausible URL now would produce a manifest that looks correct and
// resolves to nothing, which is precisely the failure this repository keeps
// finding. It lands when the endpoint does.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Materialise the scoped plugins' skills.
//
// emit() above writes single file bodies. A skill is a directory, so it needs
// its own copy and its own comparison. Drift here rolls into the same counter
// the manifests use, which is what puts it behind `npm test`.
// ---------------------------------------------------------------------------
let subsetStale = 0;
const drift = (msg) => { subsetStale++; if (check) console.error(`x ${msg}`); };
const listDir = (p) => (existsSync(p) ? readdirSync(p).filter((n) => n !== '.DS_Store').sort() : []);
const flatten = (root, prefix = '') => {
  const out = [];
  for (const name of readdirSync(root).filter((n) => n !== '.DS_Store').sort()) {
    const full = join(root, name);
    if (statSync(full).isDirectory()) out.push(...flatten(full, `${prefix}${name}/`));
    else out.push([`${prefix}${name}`, readFileSync(full)]);
  }
  return out;
};

for (const s of SCOPED) {
  const dir = join('plugins', s.name, 'skills');
  const want = [...s.skills].sort();
  if (!check) { rmSync(dir, { recursive: true, force: true }); mkdirSync(dir, { recursive: true }); }
  const have = listDir(dir);
  if (have.join(',') !== want.join(',')) drift(`${dir} holds [${have.join(', ')}], expected [${want.join(', ')}]`);
  for (const id of want) {
    const dest = join(dir, id);
    const source = join('skills', id);
    if (check) {
      if (!existsSync(dest)) { drift(`${dest} is missing`); continue; }
      const a = flatten(source);
      const b = flatten(dest);
      if (a.length !== b.length || a.some(([p, body], i) => b[i][0] !== p || !body.equals(b[i][1]))) {
        drift(`${dest} differs from skills/${id}, so it was edited by hand or its source moved on`);
      }
    } else {
      cpSync(source, dest, { recursive: true });
    }
  }
  if (!check) console.log(`  wrote ${dir} (${want.length} skills)`);
}

// ORPHAN SWEEP. A plugin dropped from catalog/plugins.json leaves a folder that
// nothing generates and nothing compares, so it would ship forever. The
// manifest diff below cannot see it either: it only walks files we still emit.
if (existsSync('plugins')) {
  const known = new Set(SCOPED.map((s) => s.name));
  for (const name of readdirSync('plugins').filter((n) => n !== '.DS_Store')) {
    if (known.has(name)) continue;
    if (check) drift(`plugins/${name} is not in catalog/plugins.json`);
    else { rmSync(join('plugins', name), { recursive: true, force: true }); console.log(`  removed plugins/${name}, no longer in catalog/plugins.json`); }
  }
}

// DANGLING REFERENCES, reported and not enforced. A skill body routes to other
// skills by name. In a subset, a name can point at a skill the user did not
// install, and the agent then sends them somewhere they cannot go. This is the
// first thing that breaks when membership changes, and it is exactly how the
// Data API builder problem was found. It does not fail the run, because the
// right fix is sometimes to accept the reference and sometimes to move the
// skill, and that is a person's call.
// Every subset produces some of these, because the catalog is densely
// cross-referenced by design: a skill hands the part of a task it does not own
// to the skill that does. Measured 2026-09-22 across these three plugins: 48
// skills name at least one absent skill, and the single biggest contributor is
// the azure-sql router, which almost every skill points at and which ships in
// the full plugin only. So the default is a count per plugin, and --dangling
// prints the list. A wall of 48 lines on every generate would be read once.
const dangling = [];
for (const s of SCOPED) {
  const carried = new Set(s.skills);
  for (const id of s.skills) {
    const body = readFileSync(join('skills', id, 'SKILL.md'), 'utf8');
    const named = present
      .map((p) => p.name)
      .filter((other) => other !== id && !carried.has(other))
      .filter((other) => new RegExp(`(^|[^a-z0-9-])${other}([^a-z0-9-]|$)`).test(body));
    if (named.length) dangling.push({ plugin: s.name, id, named });
  }
}
if (dangling.length) {
  const detail = process.argv.includes('--dangling');
  console.log('');
  for (const s of SCOPED) {
    const rows = dangling.filter((d) => d.plugin === s.name);
    if (!rows.length) continue;
    console.log(`! ${s.name}: ${rows.length} of ${s.skills.length} skills name a skill this plugin does not carry`);
    if (detail) for (const r of rows) console.log(`    ${r.id} names ${r.named.join(', ')}`);
  }
  if (!detail) console.log('  Run with --dangling for the list.');
}

let stale = subsetStale;
for (const [path, body] of outputs) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === body) continue;
  stale++;
  if (check) {
    console.error(`x ${path} is out of date`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`  wrote ${path}`);
  }
}

if (check) {
  if (stale) {
    console.error(`\n${stale} generated file(s) differ from a fresh generation.`);
    console.error('Run "npm run generate" and commit the result. Do not edit generated files by hand.');
    process.exit(1);
  }
  console.log(`all ${outputs.size} generated surfaces are current`);
} else {
  console.log(`${outputs.size} surfaces generated, ${stale} changed, from ${present.length} skills on disk`);
}
